AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World Lambda

Resources:

  HelloWorldAPI:
        Type: AWS::Serverless::Api
        Properties:
          StageName: Prod
          DefinitionBody:
                    swagger: "2.0"
                    info:
                        title:
                            Ref: AWS::StackName
                    schemes:
                      - "https"
                    paths:
                      /hello/{name}:
                        get:
                          x-amazon-apigateway-integration:
                            uri:
                                Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloWorldLambda.Arn}/invocations"
                            httpMethod: "POST"
                            type: "aws_proxy"

  HelloWorldLambda:
        Type: AWS::Serverless::Function
        Properties:
          Handler: com.harprit.aws.lambda.HelloAWSLambda::handler
          Runtime: java8
          MemorySize: 512
          Timeout: 10
          CodeUri: target/hello-aws-apig-lambda-0.0.1-SNAPSHOT.jar
          Events:
            ApiEvents:
              Type: Api
              Properties:
                RestApiId: !Ref HelloWorldAPI
                Path: /hello/{name}
                Method: GET
